### PR TITLE
Add severity argument to task

### PR DESCRIPTION
**Pull request by markwooff**
Possible solution to https://github.com/aquasecurity/trivy-azure-pipelines-task/issues/14 - looking for review.

### CODE REVIEW

**Review by Layer8Err — APPROVED** [review]
Looks good!

**Comment by markwooff** [comment]
> Looks good!

What are the next steps for getting this change merged in? Hoping to start using it in our AZDO tasks 😄

**Comment by ChrisHolman** [comment]
Any update on this? Keen to start using it.

**Comment by ferronsw** [comment]
@giorod3 fixed In #25

**Comment by markwooff** [comment]
@ferronsw thanks for pushing this change in as part of https://github.com/aquasecurity/trivy-azure-pipelines-task/pull/25. Closing this PR.

**Comment by AndrewGretton** [comment]
This looks great. When will it hit the [Marketplace](https://marketplace.visualstudio.com/items?itemName=AquaSecurityOfficial.trivy-official) though?

**Pull request closed without merging**
