### PR TITLE
feat: Update Trivy to version v0.45.1

### PR DESCRIPTION
**Pull request by simar7**
Update Trivy to version v0.45.1

re: https://github.com/aquasecurity/trivy/discussions/5258

### CODE REVIEW

**Review by Sam-Tymoshchuk — APPROVED** [review]
Look LGTM

**Review by Sam-Tymoshchuk — APPROVED** [review]

**Comment by simar7** [comment]
cc @giorod3 could you approve, merge and release a new build?

**Comment by saqwel** [comment]
I have encountered issue which can be fixed by this pull request. Could you merge it?

**Comment by Enemico** [comment]
Can this be merged please?

**Review by bisforboman — APPROVED** [review]
LGTM

**Review by giorod3 — APPROVED** [review]

**Comment by evertonlsouza** [comment]
Hey,
I use it, I did a test on my pipeline, setting the version to latest and it still keeps breaking.


Error:
Filesystem check FATAL error: check error: check failed: parse failed: failed to call hooks: post handler error: bad configuration check error: check configuration error: 4 errors occurred:
policies/cloud/policies/aws/rds/disable_cluster_skip_final_snapshot.rego:26: rego_type_error: undefined reference: cluster.skipfinalsnapshot.value
cluster.skipfinalsnapshot.value


If I use version v0.45.0 it works

**Pull request merged**
